### ISSUE TITLE
Not able to build Initial Page for DisplayQuizzesView

### ISSUE THREAD

**Issue by emmshen** [vivjd/Squiz#25]
**Describe the bug**
When building the initial page in main, error happens when we run it. This is because the table in DisplayQuizzesView is empty so we get an error. 

**To Reproduce**
1. Go to the branch 'DisplayQuizUseCase'
2. Run the main file
3. Should get a red error message saying that the table rows is null.

**Expected behavior**
No error message should appear and the screen should change to a table of all the quizzes from the database.

**Additional context**
Need a way to be able to update the empty table in the DisplayQuizzes into the stored quizzes in the database. The backend works and does output the String[][] but the table is not updated in the view.

**Comment by vivjd** [comment]
After using the debugger, the program seems to be passing in the data in correctly at all points. I suspect it has something to do with the view not being updated as I've put print statements in there to check. 

After running the debugger multiple times, I think the problem is that the `NoteView` is never updated.

**Comment by vivjd** [comment]
This is now resolved after going to office hours with @emmshen . The issue was because a new table object was created every time the view was called, subsequently not updating the display. We now modify the initial table object every time the use case is called.
